### ISSUE TITLE
State mutation

### ISSUE THREAD

**Issue by Default4152** [johnwonderbread/jamming#1]
Important for errors - In React we don't want to mutate the state directly. If we want to update the state, we should be using this.setState. In `App.js` you have the `removeTrack` method which sets `var array = this.state.playlistTracks;` - any changes to `array` like `array.splice(index, 1);` on line 47 will change `this.state.playlistTracks` behind the scenes as well. You can observe this by putting `console.log(this.state);` after line 47 but before `this.setState({ playlistTracks: array });`on line 49. You can read more about this on the official react documentation here: https://reactjs.org/docs/react-component.html#state

By avoiding updating the state directly, we can maintain more predictability about our applications state.

**Comment by johnwonderbread** [comment]
I've removed the previous block of code and replaced with this instead to address the state mutation issues. 

`  removeTrack(track) {
      this.setState({
        playlistTracks: this.state.playlistTracks.filter(playlistTrack => playlistTrack.id !== track.id)
      });
  }`
