### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by Default4152** [johnwonderbread/jamming#2]
Simplify - I recommend using a style guide to format your code in a way that improves the readability and organization.

We can make improvements to the indentation, semicolon usage and spacing by following a javascript (React) style guide like this one from airbnb: https://github.com/airbnb/javascript/tree/master/react

Your codes indentation and formatting is mostly good! There are just a few small changes I would make like L30-32 in `App.js`. Following this guide, there would be mostly minor changes required.

**Comment by johnwonderbread** [comment]
Addressed L30-32 in App.js. 

`  addTrack(track) {
    if (this.state.playlistTracks.find(savedTrack => savedTrack.id === track.id)) {
      return;
    } else {
      var joined = this.state.playlistTracks.concat(track);
      this.setState({ playlistTracks: joined })
      console.log(this.state.playlistName)
    }
    /* achieved with another method, but this is interesting: https://medium.freecodecamp.org/handling-state-in-react-four-immutable-approaches-to-consider-d1f5c00249d5
    let playlistTracks = update(this.state.playlistTracks, {$merge: {[]: }})
    this.setState(this.playlistTracks);
    ^^^ failed attempt at one of the suggestions in the medium article
    */
  }`

Addressed lines 16-28 in Playlist.js.

`  render() {
    return (
      <div className="Playlist">
        <input placeholder="New Playlist" onChange={this.handleNameChange} />
        <TrackList
          tracks={this.props.playlistTracks}
          onAdd={this.props.onAdd}
          onRemove={this.props.onRemove}
          isRemoval={true} />
        <a className="Playlist-save" onClick={this.props.onSave}>SAVE TO SPOTIFY</a>
      </div>
    )
  }`

addressed lines 41-49 in Track.js

`    return (
      <div className="Track">
        <div className="Track-information">
          <h3>{this.props.track.name}</h3>
          <p>{`${this.props.track.artist} | ${this.props.track.album}`}></p>
        </div>
        {this.renderAction()}
      </div>
    )`

addressed lines 6-17 in SearchResults.js:

`  render() {
    return (
      <div className="SearchResults">
        <h2>Results</h2>
        <TrackList
          tracks={this.props.searchRZesults}
          onAdd={this.props.onAdd}
          onRemove={this.props.onRemove}
          isRemoval={false} />
      </div>
    )
  }`

addressed lines 23-29 in SearchBar.js:

`    return (
      <div className="SearchBar">
        <input placeholder="Enter A Song, Album, or Artist"
          onChange={this.handleChange} />
        <a onClick={this.handleSearch}>SEARCH</a>
      </div>
    )`
