### ISSUE TITLE
Commented out code

### ISSUE THREAD

**Issue by Default4152** [johnwonderbread/jamming#3]
Simplify - It's recommended to not leave any commented out code. Examples are like the code at the bottom inside of `Spotify.js`. If you want to remove some code and are unsure when you'll need it again for studying or what not, you can remove it and store these changes inside of `git` - if you ever find you need to get that code back, you can refer to your `git` commit history.

**Comment by johnwonderbread** [comment]
Noted for production products in the future. For a personal work in progress, I kind of prefer it as notes to go back and review/learn from/ideas to explore. But totally get it in a professional development environment.
