### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [johnwonderbread/jamming#4]
Grade: **Meets Expectations**

Very nice job on this project! It was super simple to setup without any errors. The app worked flawlessly and allowed me to save some songs to a playlist. I thought your code looked mostly good and your commits were frequent.

Some suggestions moving forward:
1. Go through your application and fix all instances of direct state mutation - while this isn't a problem now, it will be if the app were to grow in size.
2. While your code formatting was mostly good, there are small improvements that could be made. I recommend learning about how `airbnb` styles their React and try to apply some of it to your project.
3. Take advantage of `git` and remove commented out code.

Good work!

**Comment by johnwonderbread** [comment]
Thanks for the feedback @Nulcon ! Appreciate you taking the time to review the code.
